// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: openoffload.proto
// Original file comments:
// Copyright (C) 2020 AT&T Intellectual Property. All rights reserved.
// Copyright (C) 2020 Palo Alto Networks Intellectual Property. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//
#ifndef GRPC_openoffload_2eproto__INCLUDED
#define GRPC_openoffload_2eproto__INCLUDED

#include "openoffload.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace openoffload {
namespace v1_1 {

//
// The session table was combined with the statistices service
// in v1alpha4 to simplfy the code.
//
class SessionTable final {
 public:
  static constexpr char const* service_full_name() {
    return "openoffload.v1_1.SessionTable";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    //
    // Adds a session
    // This was changed in v1alpha4 to be a streaming API, for performance
    // reasons.
    std::unique_ptr< ::grpc::ClientWriterInterface< ::openoffload::v1_1::sessionRequest>> addSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::openoffload::v1_1::sessionRequest>>(addSessionRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::openoffload::v1_1::sessionRequest>> AsyncaddSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::openoffload::v1_1::sessionRequest>>(AsyncaddSessionRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::openoffload::v1_1::sessionRequest>> PrepareAsyncaddSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::openoffload::v1_1::sessionRequest>>(PrepareAsyncaddSessionRaw(context, response, cq));
    }
    //
    // Obtains the session 
    virtual ::grpc::Status getSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::openoffload::v1_1::sessionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>> AsyncgetSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>>(AsyncgetSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>> PrepareAsyncgetSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>>(PrepareAsyncgetSessionRaw(context, request, cq));
    }
    //
    // Delete a session
    virtual ::grpc::Status deleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::openoffload::v1_1::sessionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>> AsyncdeleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>>(AsyncdeleteSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>> PrepareAsyncdeleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>>(PrepareAsyncdeleteSessionRaw(context, request, cq));
    }
    //
    // Stream back all current sessions
    // rpc getAllSessions(statisticsRequestArgs) returns (stream sessionResponse) {}
    virtual ::grpc::Status getAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::openoffload::v1_1::sessionResponses* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponses>> AsyncgetAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponses>>(AsyncgetAllSessionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponses>> PrepareAsyncgetAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponses>>(PrepareAsyncgetAllSessionsRaw(context, request, cq));
    }
    //
    // statistics as a outgoing session from the WB to Applications ?
    // grpc seems to need a request input streamId is a placeholder
    std::unique_ptr< ::grpc::ClientReaderInterface< ::openoffload::v1_1::sessionResponse>> getClosedSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::openoffload::v1_1::sessionResponse>>(getClosedSessionsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::openoffload::v1_1::sessionResponse>> AsyncgetClosedSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::openoffload::v1_1::sessionResponse>>(AsyncgetClosedSessionsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::openoffload::v1_1::sessionResponse>> PrepareAsyncgetClosedSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::openoffload::v1_1::sessionResponse>>(PrepareAsyncgetClosedSessionsRaw(context, request, cq));
    }
    //
    // Shutdown Server method
    //
    virtual ::grpc::Status shutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::openoffload::v1_1::shutdownResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::shutdownResponse>> AsyncshutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::shutdownResponse>>(AsyncshutdownServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::shutdownResponse>> PrepareAsyncshutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::shutdownResponse>>(PrepareAsyncshutdownServerRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      //
      // Adds a session
      // This was changed in v1alpha4 to be a streaming API, for performance
      // reasons.
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void addSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::ClientWriteReactor< ::openoffload::v1_1::sessionRequest>* reactor) = 0;
      #else
      virtual void addSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::experimental::ClientWriteReactor< ::openoffload::v1_1::sessionRequest>* reactor) = 0;
      #endif
      //
      // Obtains the session 
      virtual void getSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      //
      // Delete a session
      virtual void deleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void deleteSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void deleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void deleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void deleteSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void deleteSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      //
      // Stream back all current sessions
      // rpc getAllSessions(statisticsRequestArgs) returns (stream sessionResponse) {}
      virtual void getAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs* request, ::openoffload::v1_1::sessionResponses* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getAllSessions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponses* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs* request, ::openoffload::v1_1::sessionResponses* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs* request, ::openoffload::v1_1::sessionResponses* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getAllSessions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponses* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getAllSessions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponses* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      //
      // statistics as a outgoing session from the WB to Applications ?
      // grpc seems to need a request input streamId is a placeholder
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getClosedSessions(::grpc::ClientContext* context, ::openoffload::v1_1::sessionRequestArgs* request, ::grpc::ClientReadReactor< ::openoffload::v1_1::sessionResponse>* reactor) = 0;
      #else
      virtual void getClosedSessions(::grpc::ClientContext* context, ::openoffload::v1_1::sessionRequestArgs* request, ::grpc::experimental::ClientReadReactor< ::openoffload::v1_1::sessionResponse>* reactor) = 0;
      #endif
      //
      // Shutdown Server method
      //
      virtual void shutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest* request, ::openoffload::v1_1::shutdownResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void shutdownServer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::shutdownResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void shutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest* request, ::openoffload::v1_1::shutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void shutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest* request, ::openoffload::v1_1::shutdownResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void shutdownServer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::shutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void shutdownServer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::shutdownResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientWriterInterface< ::openoffload::v1_1::sessionRequest>* addSessionRaw(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::openoffload::v1_1::sessionRequest>* AsyncaddSessionRaw(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::openoffload::v1_1::sessionRequest>* PrepareAsyncaddSessionRaw(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>* AsyncgetSessionRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>* PrepareAsyncgetSessionRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>* AsyncdeleteSessionRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponse>* PrepareAsyncdeleteSessionRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponses>* AsyncgetAllSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::sessionResponses>* PrepareAsyncgetAllSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::openoffload::v1_1::sessionResponse>* getClosedSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::openoffload::v1_1::sessionResponse>* AsyncgetClosedSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::openoffload::v1_1::sessionResponse>* PrepareAsyncgetClosedSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::shutdownResponse>* AsyncshutdownServerRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::openoffload::v1_1::shutdownResponse>* PrepareAsyncshutdownServerRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientWriter< ::openoffload::v1_1::sessionRequest>> addSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::openoffload::v1_1::sessionRequest>>(addSessionRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::openoffload::v1_1::sessionRequest>> AsyncaddSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::openoffload::v1_1::sessionRequest>>(AsyncaddSessionRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::openoffload::v1_1::sessionRequest>> PrepareAsyncaddSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::openoffload::v1_1::sessionRequest>>(PrepareAsyncaddSessionRaw(context, response, cq));
    }
    ::grpc::Status getSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::openoffload::v1_1::sessionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>> AsyncgetSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>>(AsyncgetSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>> PrepareAsyncgetSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>>(PrepareAsyncgetSessionRaw(context, request, cq));
    }
    ::grpc::Status deleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::openoffload::v1_1::sessionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>> AsyncdeleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>>(AsyncdeleteSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>> PrepareAsyncdeleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>>(PrepareAsyncdeleteSessionRaw(context, request, cq));
    }
    ::grpc::Status getAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::openoffload::v1_1::sessionResponses* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponses>> AsyncgetAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponses>>(AsyncgetAllSessionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponses>> PrepareAsyncgetAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponses>>(PrepareAsyncgetAllSessionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::openoffload::v1_1::sessionResponse>> getClosedSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::openoffload::v1_1::sessionResponse>>(getClosedSessionsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::openoffload::v1_1::sessionResponse>> AsyncgetClosedSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::openoffload::v1_1::sessionResponse>>(AsyncgetClosedSessionsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::openoffload::v1_1::sessionResponse>> PrepareAsyncgetClosedSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::openoffload::v1_1::sessionResponse>>(PrepareAsyncgetClosedSessionsRaw(context, request, cq));
    }
    ::grpc::Status shutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::openoffload::v1_1::shutdownResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::shutdownResponse>> AsyncshutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::shutdownResponse>>(AsyncshutdownServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::shutdownResponse>> PrepareAsyncshutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::shutdownResponse>>(PrepareAsyncshutdownServerRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void addSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::ClientWriteReactor< ::openoffload::v1_1::sessionRequest>* reactor) override;
      #else
      void addSession(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::experimental::ClientWriteReactor< ::openoffload::v1_1::sessionRequest>* reactor) override;
      #endif
      void getSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, std::function<void(::grpc::Status)>) override;
      void getSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void deleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, std::function<void(::grpc::Status)>) override;
      void deleteSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void deleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void deleteSession(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void deleteSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void deleteSession(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void getAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs* request, ::openoffload::v1_1::sessionResponses* response, std::function<void(::grpc::Status)>) override;
      void getAllSessions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponses* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs* request, ::openoffload::v1_1::sessionResponses* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getAllSessions(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs* request, ::openoffload::v1_1::sessionResponses* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getAllSessions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponses* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getAllSessions(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::sessionResponses* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getClosedSessions(::grpc::ClientContext* context, ::openoffload::v1_1::sessionRequestArgs* request, ::grpc::ClientReadReactor< ::openoffload::v1_1::sessionResponse>* reactor) override;
      #else
      void getClosedSessions(::grpc::ClientContext* context, ::openoffload::v1_1::sessionRequestArgs* request, ::grpc::experimental::ClientReadReactor< ::openoffload::v1_1::sessionResponse>* reactor) override;
      #endif
      void shutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest* request, ::openoffload::v1_1::shutdownResponse* response, std::function<void(::grpc::Status)>) override;
      void shutdownServer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::shutdownResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void shutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest* request, ::openoffload::v1_1::shutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void shutdownServer(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest* request, ::openoffload::v1_1::shutdownResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void shutdownServer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::shutdownResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void shutdownServer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::openoffload::v1_1::shutdownResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientWriter< ::openoffload::v1_1::sessionRequest>* addSessionRaw(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response) override;
    ::grpc::ClientAsyncWriter< ::openoffload::v1_1::sessionRequest>* AsyncaddSessionRaw(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::openoffload::v1_1::sessionRequest>* PrepareAsyncaddSessionRaw(::grpc::ClientContext* context, ::openoffload::v1_1::addSessionResponse* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>* AsyncgetSessionRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>* PrepareAsyncgetSessionRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>* AsyncdeleteSessionRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponse>* PrepareAsyncdeleteSessionRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponses>* AsyncgetAllSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::sessionResponses>* PrepareAsyncgetAllSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::openoffload::v1_1::sessionResponse>* getClosedSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request) override;
    ::grpc::ClientAsyncReader< ::openoffload::v1_1::sessionResponse>* AsyncgetClosedSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::openoffload::v1_1::sessionResponse>* PrepareAsyncgetClosedSessionsRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::sessionRequestArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::shutdownResponse>* AsyncshutdownServerRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::openoffload::v1_1::shutdownResponse>* PrepareAsyncshutdownServerRaw(::grpc::ClientContext* context, const ::openoffload::v1_1::shutdownRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_addSession_;
    const ::grpc::internal::RpcMethod rpcmethod_getSession_;
    const ::grpc::internal::RpcMethod rpcmethod_deleteSession_;
    const ::grpc::internal::RpcMethod rpcmethod_getAllSessions_;
    const ::grpc::internal::RpcMethod rpcmethod_getClosedSessions_;
    const ::grpc::internal::RpcMethod rpcmethod_shutdownServer_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    //
    // Adds a session
    // This was changed in v1alpha4 to be a streaming API, for performance
    // reasons.
    virtual ::grpc::Status addSession(::grpc::ServerContext* context, ::grpc::ServerReader< ::openoffload::v1_1::sessionRequest>* reader, ::openoffload::v1_1::addSessionResponse* response);
    //
    // Obtains the session 
    virtual ::grpc::Status getSession(::grpc::ServerContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response);
    //
    // Delete a session
    virtual ::grpc::Status deleteSession(::grpc::ServerContext* context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response);
    //
    // Stream back all current sessions
    // rpc getAllSessions(statisticsRequestArgs) returns (stream sessionResponse) {}
    virtual ::grpc::Status getAllSessions(::grpc::ServerContext* context, const ::openoffload::v1_1::sessionRequestArgs* request, ::openoffload::v1_1::sessionResponses* response);
    //
    // statistics as a outgoing session from the WB to Applications ?
    // grpc seems to need a request input streamId is a placeholder
    virtual ::grpc::Status getClosedSessions(::grpc::ServerContext* context, const ::openoffload::v1_1::sessionRequestArgs* request, ::grpc::ServerWriter< ::openoffload::v1_1::sessionResponse>* writer);
    //
    // Shutdown Server method
    //
    virtual ::grpc::Status shutdownServer(::grpc::ServerContext* context, const ::openoffload::v1_1::shutdownRequest* request, ::openoffload::v1_1::shutdownResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_addSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_addSession() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_addSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::openoffload::v1_1::sessionRequest>* /*reader*/, ::openoffload::v1_1::addSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddSession(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::openoffload::v1_1::addSessionResponse, ::openoffload::v1_1::sessionRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getSession() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_getSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetSession(::grpc::ServerContext* context, ::openoffload::v1_1::sessionId* request, ::grpc::ServerAsyncResponseWriter< ::openoffload::v1_1::sessionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_deleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_deleteSession() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_deleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status deleteSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdeleteSession(::grpc::ServerContext* context, ::openoffload::v1_1::sessionId* request, ::grpc::ServerAsyncResponseWriter< ::openoffload::v1_1::sessionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getAllSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getAllSessions() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_getAllSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAllSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::openoffload::v1_1::sessionResponses* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetAllSessions(::grpc::ServerContext* context, ::openoffload::v1_1::sessionRequestArgs* request, ::grpc::ServerAsyncResponseWriter< ::openoffload::v1_1::sessionResponses>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getClosedSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getClosedSessions() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_getClosedSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getClosedSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::grpc::ServerWriter< ::openoffload::v1_1::sessionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetClosedSessions(::grpc::ServerContext* context, ::openoffload::v1_1::sessionRequestArgs* request, ::grpc::ServerAsyncWriter< ::openoffload::v1_1::sessionResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(4, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_shutdownServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_shutdownServer() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_shutdownServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status shutdownServer(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::shutdownRequest* /*request*/, ::openoffload::v1_1::shutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestshutdownServer(::grpc::ServerContext* context, ::openoffload::v1_1::shutdownRequest* request, ::grpc::ServerAsyncResponseWriter< ::openoffload::v1_1::shutdownResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_addSession<WithAsyncMethod_getSession<WithAsyncMethod_deleteSession<WithAsyncMethod_getAllSessions<WithAsyncMethod_getClosedSessions<WithAsyncMethod_shutdownServer<Service > > > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_addSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_addSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackClientStreamingHandler< ::openoffload::v1_1::sessionRequest, ::openoffload::v1_1::addSessionResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::openoffload::v1_1::addSessionResponse* response) { return this->addSession(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_addSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::openoffload::v1_1::sessionRequest>* /*reader*/, ::openoffload::v1_1::addSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::openoffload::v1_1::sessionRequest>* addSession(
      ::grpc::CallbackServerContext* /*context*/, ::openoffload::v1_1::addSessionResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::openoffload::v1_1::sessionRequest>* addSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::openoffload::v1_1::addSessionResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response) { return this->getSession(context, request, response); }));}
    void SetMessageAllocatorFor_getSession(
        ::grpc::experimental::MessageAllocator< ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_getSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getSession(
      ::grpc::CallbackServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_deleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_deleteSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::openoffload::v1_1::sessionId* request, ::openoffload::v1_1::sessionResponse* response) { return this->deleteSession(context, request, response); }));}
    void SetMessageAllocatorFor_deleteSession(
        ::grpc::experimental::MessageAllocator< ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_deleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status deleteSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* deleteSession(
      ::grpc::CallbackServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* deleteSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getAllSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getAllSessions() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::openoffload::v1_1::sessionRequestArgs, ::openoffload::v1_1::sessionResponses>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::openoffload::v1_1::sessionRequestArgs* request, ::openoffload::v1_1::sessionResponses* response) { return this->getAllSessions(context, request, response); }));}
    void SetMessageAllocatorFor_getAllSessions(
        ::grpc::experimental::MessageAllocator< ::openoffload::v1_1::sessionRequestArgs, ::openoffload::v1_1::sessionResponses>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::openoffload::v1_1::sessionRequestArgs, ::openoffload::v1_1::sessionResponses>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_getAllSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAllSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::openoffload::v1_1::sessionResponses* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getAllSessions(
      ::grpc::CallbackServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::openoffload::v1_1::sessionResponses* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getAllSessions(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::openoffload::v1_1::sessionResponses* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getClosedSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getClosedSessions() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(4,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::openoffload::v1_1::sessionRequestArgs, ::openoffload::v1_1::sessionResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::openoffload::v1_1::sessionRequestArgs* request) { return this->getClosedSessions(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_getClosedSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getClosedSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::grpc::ServerWriter< ::openoffload::v1_1::sessionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::openoffload::v1_1::sessionResponse>* getClosedSessions(
      ::grpc::CallbackServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::openoffload::v1_1::sessionResponse>* getClosedSessions(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_shutdownServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_shutdownServer() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(5,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::openoffload::v1_1::shutdownRequest, ::openoffload::v1_1::shutdownResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::openoffload::v1_1::shutdownRequest* request, ::openoffload::v1_1::shutdownResponse* response) { return this->shutdownServer(context, request, response); }));}
    void SetMessageAllocatorFor_shutdownServer(
        ::grpc::experimental::MessageAllocator< ::openoffload::v1_1::shutdownRequest, ::openoffload::v1_1::shutdownResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(5);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::openoffload::v1_1::shutdownRequest, ::openoffload::v1_1::shutdownResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_shutdownServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status shutdownServer(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::shutdownRequest* /*request*/, ::openoffload::v1_1::shutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* shutdownServer(
      ::grpc::CallbackServerContext* /*context*/, const ::openoffload::v1_1::shutdownRequest* /*request*/, ::openoffload::v1_1::shutdownResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* shutdownServer(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::openoffload::v1_1::shutdownRequest* /*request*/, ::openoffload::v1_1::shutdownResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_addSession<ExperimentalWithCallbackMethod_getSession<ExperimentalWithCallbackMethod_deleteSession<ExperimentalWithCallbackMethod_getAllSessions<ExperimentalWithCallbackMethod_getClosedSessions<ExperimentalWithCallbackMethod_shutdownServer<Service > > > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_addSession<ExperimentalWithCallbackMethod_getSession<ExperimentalWithCallbackMethod_deleteSession<ExperimentalWithCallbackMethod_getAllSessions<ExperimentalWithCallbackMethod_getClosedSessions<ExperimentalWithCallbackMethod_shutdownServer<Service > > > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_addSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_addSession() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_addSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::openoffload::v1_1::sessionRequest>* /*reader*/, ::openoffload::v1_1::addSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getSession() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_getSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_deleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_deleteSession() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_deleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status deleteSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getAllSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getAllSessions() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_getAllSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAllSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::openoffload::v1_1::sessionResponses* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getClosedSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getClosedSessions() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_getClosedSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getClosedSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::grpc::ServerWriter< ::openoffload::v1_1::sessionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_shutdownServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_shutdownServer() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_shutdownServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status shutdownServer(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::shutdownRequest* /*request*/, ::openoffload::v1_1::shutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_addSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_addSession() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_addSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::openoffload::v1_1::sessionRequest>* /*reader*/, ::openoffload::v1_1::addSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddSession(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getSession() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_getSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_deleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_deleteSession() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_deleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status deleteSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdeleteSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getAllSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getAllSessions() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_getAllSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAllSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::openoffload::v1_1::sessionResponses* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetAllSessions(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getClosedSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getClosedSessions() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_getClosedSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getClosedSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::grpc::ServerWriter< ::openoffload::v1_1::sessionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetClosedSessions(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(4, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_shutdownServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_shutdownServer() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_shutdownServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status shutdownServer(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::shutdownRequest* /*request*/, ::openoffload::v1_1::shutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestshutdownServer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_addSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_addSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->addSession(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_addSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::openoffload::v1_1::sessionRequest>* /*reader*/, ::openoffload::v1_1::addSessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* addSession(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* addSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getSession(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_getSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_deleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_deleteSession() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->deleteSession(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_deleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status deleteSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* deleteSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* deleteSession(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getAllSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getAllSessions() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getAllSessions(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_getAllSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAllSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::openoffload::v1_1::sessionResponses* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getAllSessions(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getAllSessions(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getClosedSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getClosedSessions() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(4,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->getClosedSessions(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_getClosedSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getClosedSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::grpc::ServerWriter< ::openoffload::v1_1::sessionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* getClosedSessions(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* getClosedSessions(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_shutdownServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_shutdownServer() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(5,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->shutdownServer(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_shutdownServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status shutdownServer(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::shutdownRequest* /*request*/, ::openoffload::v1_1::shutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* shutdownServer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* shutdownServer(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getSession() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>* streamer) {
                       return this->StreamedgetSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::openoffload::v1_1::sessionId,::openoffload::v1_1::sessionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_deleteSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_deleteSession() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::openoffload::v1_1::sessionId, ::openoffload::v1_1::sessionResponse>* streamer) {
                       return this->StreameddeleteSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_deleteSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status deleteSession(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionId* /*request*/, ::openoffload::v1_1::sessionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreameddeleteSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::openoffload::v1_1::sessionId,::openoffload::v1_1::sessionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getAllSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getAllSessions() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::openoffload::v1_1::sessionRequestArgs, ::openoffload::v1_1::sessionResponses>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::openoffload::v1_1::sessionRequestArgs, ::openoffload::v1_1::sessionResponses>* streamer) {
                       return this->StreamedgetAllSessions(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getAllSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getAllSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::openoffload::v1_1::sessionResponses* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetAllSessions(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::openoffload::v1_1::sessionRequestArgs,::openoffload::v1_1::sessionResponses>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_shutdownServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_shutdownServer() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::openoffload::v1_1::shutdownRequest, ::openoffload::v1_1::shutdownResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::openoffload::v1_1::shutdownRequest, ::openoffload::v1_1::shutdownResponse>* streamer) {
                       return this->StreamedshutdownServer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_shutdownServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status shutdownServer(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::shutdownRequest* /*request*/, ::openoffload::v1_1::shutdownResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedshutdownServer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::openoffload::v1_1::shutdownRequest,::openoffload::v1_1::shutdownResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getSession<WithStreamedUnaryMethod_deleteSession<WithStreamedUnaryMethod_getAllSessions<WithStreamedUnaryMethod_shutdownServer<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_getClosedSessions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_getClosedSessions() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::openoffload::v1_1::sessionRequestArgs, ::openoffload::v1_1::sessionResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerSplitStreamer<
                     ::openoffload::v1_1::sessionRequestArgs, ::openoffload::v1_1::sessionResponse>* streamer) {
                       return this->StreamedgetClosedSessions(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_getClosedSessions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getClosedSessions(::grpc::ServerContext* /*context*/, const ::openoffload::v1_1::sessionRequestArgs* /*request*/, ::grpc::ServerWriter< ::openoffload::v1_1::sessionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedgetClosedSessions(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::openoffload::v1_1::sessionRequestArgs,::openoffload::v1_1::sessionResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_getClosedSessions<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_getSession<WithStreamedUnaryMethod_deleteSession<WithStreamedUnaryMethod_getAllSessions<WithSplitStreamingMethod_getClosedSessions<WithStreamedUnaryMethod_shutdownServer<Service > > > > > StreamedService;
};

}  // namespace v1_1
}  // namespace openoffload


#endif  // GRPC_openoffload_2eproto__INCLUDED
